Dev
ssailor96/duplicate-file-checker pull request #1
Opened 2022-09-27 21:04 UTC by ssailor96

2022-09-28 17:06 UTC, ssailor commented
The functionality looks to be working as I would expect for this. Here are a few things I noticed that I believe would be worth considering in the future.

1. The application only works at the moment by prompting a user for input after they launch the program. This works however it does not allow for someone to be able to use this application in any form of automation. I believe this could be valuable if I wanted to perform a bunch of different hashing operations that I would trigger by using a bash script. You could change that by adding the ability for users to provide command line arguments. So as an example if someone wanted to get the hashes of a directory they could provide a command line flag with the directory name (possibly a -d flag. Then the app would run, generate the file then end which would allow the next item in a script to run. The app could be set up to still run interactively if no command line arguments are provided however if command line args are used then it would just run without having to run interactivity.

2. Since this app is meant to run on the command line I'd recommend changing the main file name to something more specific such as duplicate_checker.py 

3. I notice that 2 files are generated when you finish a hashing run but it looks like they return pretty much the same information. The duplicates file just looks like it's a shorter list of only duplicates. Since your object has a flag of isDuplicate this information could easily be parsed out. I'd recommend returning only a single file and/or giving the user the option to get the full report or just the duplicates. Either way, I think returning a single file may be more clear. 

4. After the program runs it only tells the user if there were duplicates or not and doesn't present the users with any further helpful information. I would recommend that if you're going to prompt users for input to add some more functionality after a run has been completed. This could be an option to see in the console the number of duplicates found along with a list of filenames. Additionally, other features such as asking the user if they would like to run another comparison could enhance the application as well.

2022-09-28 17:08 UTC, ssailor commented
There is an issue with the way you are creating file names. Colons are not allowed in filenames on windows. Using a datetime for filenames is fine but I'd recommend making sure to use characters that are safe across all OS.

2022-09-28 17:10 UTC, ssailor requested changes
Need to at least fix the filename issue to use safe characters. I also recommend making some of the other changes I called out.

2022-09-28 17:10 UTC, ssailor commented on requirements.txt
> +humanize==4.3.0
Unless you need the exact version of 4.3 you could use version specifiers to allow minor and patch versions to be used but not update to the next major version. To do that you could change this to be `humanize~=4.3`
Check out this link for more on version specifiers: https://peps.python.org/pep-0440/#examples

2022-09-28 17:10 UTC, ssailor commented on README.md
> +- Make sure to use correct input (a path to a file or directory). If incorrect input is used, the program will exit and need to be run again.
You may want to specify if the app requires an absolute path or a relative path.

2022-09-28 17:10 UTC, ssailor commented on README.md
> +To check if two files are the same, enter a path to a file. To check for duplicates in an entire directory, enter a path to a directory.
You may want to specify if the duplicates for the directory check checks subfolders or if it sticks to the top level.

2022-09-28 17:10 UTC, ssailor commented on README.md
> +## Outputs
It might be worth showing examples of the output for each file so users can see what the data structure of the output should look like.

2022-09-28 17:10 UTC, ssailor commented on README.md
> +## Prerequisites
Since you are using an external package I'd recommend adding a small getting started section showing to create and start a virtual environment along with showing how to use the requirements.txt to download dependencies.

2022-09-28 17:10 UTC, ssailor commented on app.py
> +def getInfo(pathList, fileList):
Naming conventions for python methods are all lower cases with words separated by underscores. I'd recommend changing the method names to match the naming convention. For more info here is a quick article that should help: https://www.techversantinfotech.com/python-naming-conventions-points-you-should-know/#:~:text=Method%20name%20in%20Python,it%20needs%20to%20be%20mangled.

2022-09-28 17:10 UTC, ssailor commented on app.py
> +    print("System: " + str(platform.system()))
You may want to consider writing this info to the JSON output files. You could create a parent object containing the run information including this nest the hashing info in a child object called results or something. Not a requirement just a thought.

2022-09-28 17:10 UTC, ssailor commented on app.py
> +            modTimeStamp).strftime('%Y-%m-%d--%H-%M-%S')
I would recommend changing both the modTime and createTime to use the ISO 8601 standard. Here is some info on that https://pythontic.com/datetime/datetime/isoformat

2022-09-28 18:15 UTC, ssailor96 commented on requirements.txt
> +humanize==4.3.0
Fixed issue

2022-09-29 15:30 UTC, ssailor96 commented on app.py
> +    print("System: " + str(platform.system()))
Will consider this for future versions.

2022-09-29 16:17 UTC, ssailor96 commented
@ssailor 
> The functionality looks to be working as I would expect for this. Here are a few things I noticed that I believe would be worth considering in the future.
> 
> 1. The application only works at the moment by prompting a user for input after they launch the program. This works however it does not allow for someone to be able to use this application in any form of automation. I believe this could be valuable if I wanted to perform a bunch of different hashing operations that I would trigger by using a bash script. You could change that by adding the ability for users to provide command line arguments. So as an example if someone wanted to get the hashes of a directory they could provide a command line flag with the directory name (possibly a -d flag. Then the app would run, generate the file then end which would allow the next item in a script to run. The app could be set up to still run interactively if no command line arguments are provided however if command line args are used then it would just run without having to run interactivity.

I appreciate the feedback. I don't think this needs to be a v1.0 item however I will consider making this change in the future.

> 2. Since this app is meant to run on the command line I'd recommend changing the main file name to something more specific such as duplicate_checker.py

This change is done.

> 3. I notice that 2 files are generated when you finish a hashing run but it looks like they return pretty much the same information. The duplicates file just looks like it's a shorter list of only duplicates. Since your object has a flag of isDuplicate this information could easily be parsed out. I'd recommend returning only a single file and/or giving the user the option to get the full report or just the duplicates. Either way, I think returning a single file may be more clear.

I partially did this, I decided to just make this one file for simplicity.

> 4. After the program runs it only tells the user if there were duplicates or not and doesn't present the users with any further helpful information. I would recommend that if you're going to prompt users for input to add some more functionality after a run has been completed. This could be an option to see in the console the number of duplicates found along with a list of filenames. Additionally, other features such as asking the user if they would like to run another comparison could enhance the application as well.

I added some functionality for this, I added info about the run as output in the console however I'm not doing the reprompt as part of v1.0

2022-09-29 18:44 UTC, ssailor96 commented on app.py
> +            modTimeStamp).strftime('%Y-%m-%d--%H-%M-%S')
Changes have been made to meet the ISO 8601 standard.

2022-09-29 18:45 UTC, ssailor96 commented on app.py
> +def getInfo(pathList, fileList):
Method and variable names have been changed to match python naming conventions. The only exceptions are variables being used in the output JSON file, those are named to match JSON naming conventions.

2022-10-03 16:15 UTC, ssailor96 commented on README.md
> +- Make sure to use correct input (a path to a file or directory). If incorrect input is used, the program will exit and need to be run again.
I have made this change.

2022-10-03 16:15 UTC, ssailor96 commented on README.md
> +To check if two files are the same, enter a path to a file. To check for duplicates in an entire directory, enter a path to a directory.
Updated README to specify this.

2022-10-03 16:16 UTC, ssailor96 commented on README.md
> +## Outputs
File output and console output added to README.

2022-10-03 16:16 UTC, ssailor96 commented on README.md
> +## Prerequisites
Getting started section added to README.

2022-10-04 13:53 UTC, ssailor approved these changes
Looks good, go ahead and merge. Make sure to tag it as the v.1.0.0 release in main.

2022-10-04 18:28 UTC, merged