Output changes made.
ssailor96/duplicate-file-checker pull request #4
Opened 2022-09-28 21:40 UTC by ssailor96

Number of output files reduced from 2 to 1. Duplicate file names and number of duplicates are now printed to the console.

2022-09-28 21:59 UTC, ssailor commented
You should add an entry to your .gitignore to ensure that output files you generate locally don't get checked into the repo.

2022-09-28 22:07 UTC, ssailor requested changes

2022-09-28 22:07 UTC, ssailor commented on duplicate_checker.py
> +        numDuplicates = 0
I would use the len() method to print the number of duplicates. https://www.w3schools.com/python/ref_func_len.asp

2022-09-28 22:07 UTC, ssailor commented on duplicate_checker.py
> +    outputFileName = "metadata_" + currentTime + ".json"
I recommend giving the output files a more meaningful name such as hash_report-xxxxx. I also recommend reformating the date that is generated to remove the periods. You can use the strftime method on a DateTime to print a format. I recommend using the format strftime(%Y-%m-%dT%H-%M-%S"). Using this I would expect the output name to be something like hash_report-2022-09-28T14-14-22.json.

2022-09-29 14:52 UTC, ssailor96 commented on duplicate_checker.py
> +        numDuplicates = 0
Cannot use length function in this case, I am finding duplicates using the isDuplicate attribute.

2022-09-29 15:06 UTC, ssailor96 commented on duplicate_checker.py
> +    outputFileName = "metadata_" + currentTime + ".json"
The output file name format has been updated.

2022-09-29 15:18 UTC, ssailor commented on duplicate_checker.py
> +        numDuplicates = 0
That makes sense, sorry I missed that.

2022-09-29 15:19 UTC, ssailor commented on duplicate_checker.py
> +    outputFileName = "metadata_" + currentTime + ".json"
I ran this and can confirm, the output JSON filename is now what I expected.

2022-09-29 15:20 UTC, ssailor approved these changes
Looks good now. Go ahead and merge this PR into dev

2022-09-29 15:20 UTC, merged